### ISSUE TITLE
ToDo's für Pio-X am 1. April

### ISSUE THREAD

**Issue by demianh** [pio-x/pio-x#104]
ToDo's bis am 1.April:
  * [x] Rätsel erfassen
  * [x] Mehr Stationen erfassen an Orten wo es dünn ist bisher
  * [x] Belohnung organisieren
  * [x] Erkennungsmerkmal für MrX
  * [x] Mr.X finden (5)
  * [x] Dummy Teams erstellen
  * [x] Teamblätter drucken
  * [x] Passcodes generieren
  * [x] Passcodes drucken
  * [x] Infotext in App anpassen
  * [x] Server Ressourcen erhöhen
  * [x] Pfadi Winti Banner organisieren

Zeitplan:
11:00 Büro uSystems zum drucken
12:00 Treffen beim Salzhaus
13:00 MrX instruieren
13:30 Start Check In
14:00 Eintreffen Pios
14:30 Start Spiel
16:30 Spiel Ende
16:45 Rangverkündigung
17:00 Ende
