### ISSUE TITLE
Pio-X 2019 ORGA META

### ISSUE THREAD

**Issue by e-monkey** [pio-x/pio-x#163]
ToDo's:
  * [x] Rätsel erfassen
  * [x] Winti Map laden und Stationendichte prüfen
  * [x] Belohnung organisieren
  * [x] Erkennungsmerkmal für MrX
  * [x] Mr.X finden (5)
  * [x] Dummy Teams erstellen
  * [x] Teamblätter drucken
  * [x] Passcodes generieren
  * [x] Passcodes drucken
  * [x] Infotext in App anpassen
  * [ ] Server Ressourcen erhöhen

Zeitplan:
11:00 Büro uSystems zum drucken
12:00 Treffen beim Salzhaus
13:00 MrX instruieren
13:30 Start Check In
14:00 Eintreffen Pios
14:30 Start Spiel
16:30 Spiel Ende
16:45 Rangverkündigung
17:00 Ende
